export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const NIX_INGREDIENT = 'NIX_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';


export const PURCHASE_CHEESEWICH_START = 'PURCHASE_CHEESEWICH_START';
export const PURCHASE_CHEESEWICH_SUCCESS = 'PURCHASE_CHEESEWICH_SUCCESS';
export const PURCHASE_CHEESEWICH_FAILED = 'PURCHASE_CHEESEWICH_FAILED';
export const PURCHASE_INIT = 'PURCHASE_INIT';
